Secrets/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('apps.login_app.urls',namespace = 'login')),
    url(r'^secrets/', include('apps.secrets_app.urls', namespace = 'secrets')),
    
]

apps/login_app/urls.py
from django.conf.urls import url, include
from . import views
urlpatterns = [
    url(r'^$', views.index),
    url(r'^success$', views.success),
    url(r'^login$', views.login),
    url(r'^process$', views.process)
]

apps/secrets_app/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.secrets, name='new'),
    url(r'^add$', views.add, name='add'),
    url(r'^delete/$', views.secrets, name='delete'),
    url(r'^delete/(?P<ID>\d*)/(?P<page>\w*)$', views.delete),
    url(r'^like/$', views.secrets, name='like'),
    url(r'^popular$', views.popular, name='popular'),
    url(r'^like/(?P<userID>\d*)/(?P<secretID>\d*)/(?P<page>\w*)$', views.like),
    
]

apps/login_app/models.py
from __future__ import unicode_literals
import re
from django.db import models
import bcrypt

# Create your models here.
class UserManager(models.Manager):
    def login(self, postData):
        errors = []
        data = {
            'valid': False,
            'errors': errors,
        }
        
        if not postData:
            errors.append("post only!")
            return data
        else:
            if len(postData['email']) < 2 or len(postData['password']) < 2:
                errors.append("email and password cannot be blank")
                return data
            else:
                if User.objects.filter(email = postData['email']).exists():
                    user = User.objects.get(email = postData['email'])
                    
                    try:
                        hash_pass = bcrypt.hashpw(postData['password'].encode('utf_8', 'ignore'),user.password.encode('utf_8', 'ignore'))

                        
                    except ValueError:
                        errors.append('password is incorrect')
                        return data

                    
                    
                    
                    
                    if hash_pass == user.password:
                        data['valid'] = True
                        data['user_id'] = user.id
                        return data
                    else:
                        errors.append("password is not correct")
                        return data
                else:
                    errors.append("user does not exist")
                    return data
    
    
    def register(self, postData):
        errors = []
        data = {
            'valid': False,
            'errors': errors,
        }
        if not postData:
            errors.append("post only!")
            return data
        if len(postData['first-name']) < 2 or len(postData['last-name']) < 2:
            errors.append("First and Last name must be 2 or more characters")
        # if not postData['first-name'].isalpha() or postData['last-name'].isalpha():
            # errors.append('first and last name must be letters only')
        if not re.match(r"[^@]+@[^@]+\.[^@]+", postData['email']):
            errors.append('invalid email')
        if User.objects.filter(email = postData['email']).exists():
            errors.append("email already registered. Try logging in...")
        if postData['password'] != postData['password-confirmation']:
            errors.append("passwords don't match")
        if len(postData['password']) < 4:
            errors.append("password must be at least 4 characters")
        if errors:
            return data

        
        else:
            hash_pass = bcrypt.hashpw(postData['password'].encode('utf_8', 'ignore'),bcrypt.gensalt())
            
            user = User.objects.create(first_name = postData['first-name'], last_name = postData['last-name'], email = postData['email'], password = hash_pass)
            print "*"*50
            print user.id
            data['user_id'] = user.id
            data['valid'] = True
            return data
        
class User(models.Model):
    first_name = models.TextField(max_length=100)
    last_name = models.TextField(max_length = 100)
    email = models.TextField(max_length=100)
    password = models.TextField(max_length=250)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

apps/secrets_app/models.py
from __future__ import unicode_literals
from ..login_app.models import User
from django.db import models

class SecretManager(models.Manager):
    def addSecret(self, postData):
        data = {
            'valid': False,
            'errors': []
        }
        if postData:
            
            if len(postData['secret'])< 2:
                data['errors'].append('secret must be at least 2 characters')
            else:
                user = User.objects.get(id = int(postData['user']))
                newSecret = self.create(user = user, secret = postData['secret'])
                data['valid'] = True
            return data
    
    

        

class Secret(models.Model):
    user = models.ForeignKey(User, related_name='secrets')
    secret = models.TextField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    liked_by = models.ManyToManyField(User, related_name='likes')

    objects = SecretManager()

apps/login_app/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
# Create your views here.
def index(request):
    return render(request, 'login_app/index.html')
    
def login(request):
    user = User.objects.login(request.POST)
    if user['valid']:
       
        
        request.session['user_id'] = user['user_id']

        return redirect("/success")
    else:
        for error in user['errors']:
            messages.error(request, error)
        return redirect('/')
def process(request):
    user = User.objects.register(request.POST)
    
    
    if user['valid']:
        print "user was vaild!"
        print user['user_id']
        request.session['user_id'] = user['user_id']
        return redirect('/success')
    for i in user['errors']:
        messages.error(request, i)
    return redirect("/")

def success(request):
    return redirect('secrets:new')

apps/secrets_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Secret
from ..login_app.models import User
from django.db.models import Count
# Create your views here.
def secrets(request):
    print "made it to secrets"
    all_secrets = Secret.objects.all().annotate(total_likes = Count('liked_by')).order_by('-created_at')
    user = User.objects.get(id = request.session['user_id'])
    

    context = {
        'all_secrets': all_secrets,
        'user_id': user.id,
        'user_name': user.first_name,
        'user': user
    }
    return render(request, 'secrets_app/secrets.html', context)
def add(request):
    addSecret_response = Secret.objects.addSecret(request.POST)
    if addSecret_response['valid']:
        return redirect('secrets:new')
    for error in addSecret_response['errors']:
        messages.error(request, error)
        print "*"*40
        print "redirecting to secrets:secrets "
        return redirect('/')
def delete(request, ID, page):
    
    Secret.objects.filter(id = ID).delete()
    if page == 'n':
        return redirect("secrets:new")
    else:
        return redirect("secrets:popular")

def popular(request):
    all_secrets = Secret.objects.all().annotate(total_likes = Count('liked_by')).order_by('-total_likes')
    user = User.objects.get(id = request.session['user_id'])
    

    context = {
        'all_secrets': all_secrets,
        'user_id': user.id,
        'user_name': user.first_name
    }

    return render(request, 'secrets_app/popular.html', context)

def like(request, userID, secretID, page):
    data = {
        'user_id':userID,
        'secret_id': secretID,
        
    }
    user = User.objects.get(id = data['user_id'])
    secret = Secret.objects.get(id = data['secret_id'])
    secret.liked_by.add(user)
    
    if page == 'p':
        return redirect("secrets:popular")
    
    return redirect('secrets:new')
    

apps/login_app/templates/login_app/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

    </head>
    <body>
        <form action="/process" method="post">
        {%csrf_token%}
            <fieldset>
                <legend>Register</legend>
                First Name: <input type="text" name="first-name" value=""><br>
                Last Name: <input type="text" name="last-name" value=""><br>
                Email: <input type="text" name="email" value=""><br>
                Password: <input type="password" name="password" value=""><br>
                Confirm Password: <input type="password" name="password-confirmation" value=""><br>
                <input type="submit" name="register" value="Register">
            </fieldset>
        </form>
        <br><br>
        <form action="/login" method="post">
            {%csrf_token%}
            <fieldset>

                <legend>Login</legend>
                
                Email: <input type="text" name="email" value=""><br>
                Password: <input type="password" name="password" value=""><br>

                <input type="submit" name="register" value="Login">
            </fieldset>
        </form>
        {%for message in messages%}
        <p>{{message}}</p>
        {%endfor%}
    </body>
</html>

apps/login_app/templates/login_app/success.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

    </head>
    <body>
        <h1>Success! Welcome {{request.session.user_id}}!</h1>
    </body>
</html>

apps/secrets_app/templates/secrets_app/popular.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            h1{
                display: inline-block;
            }
        </style>

    </head>
    <body>
        <h1>Most Popular Posts</h1> <a href="{% url 'secrets:new'%}">Back</a>
    {% for secrets in all_secrets %}
        <p>{{secrets.secret}} ({{ secrets.created_at|timesince}} ago) {{secrets.total_likes}} likes {%if secrets.user.id == user_id%}<a href="{%url 'secrets:delete'%}{{secrets.id}}/p">delete</a>{%else%}
        
            
        <a href="{%url 'secrets:like'%}{{user_id}}/{{secrets.id}}/p">like</a>
        

        {%endif%}</p>
        {%endfor%}





    </body>
</html>

apps/secrets_app/templates/secrets_app/secrets.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

    </head>
    <body>
        <h1>Welcome {{user_name}}!</h1>
        {%for error in messages%}
        <p>error</p>
        {%endfor%}
        <form action="{% url 'secrets:add' %}" method="post">
        {%csrf_token%}
            <input type="hidden" name="user" value="{{request.session.user_id}}">
            <textarea rows="3" cols="20" name="secret"></textarea>
            <input type="submit" name="submit" value="Post">
        </form>
        <a href="{% url 'secrets:popular' %}"> Most Popular Posts</a>
        
        {% for secrets in all_secrets|slice:":3" %}
        <p>{{secrets.secret}} ({{ secrets.created_at|timesince}} ago) {{secrets.total_likes}} likes {%if secrets.user.id == user_id%}<a href="{%url 'secrets:delete'%}{{secrets.id}}/n">delete</a>{%else%}
        <a href="{%url 'secrets:like'%}{{user_id}}/{{secrets.id}}/n">like</a>
        

        {%endif%}</p>
        {%endfor%}

        
    </body>
</html>